import type { Project } from "./types";

export const projects: Project[] = [
  {
    slug: "vg",
    title: { pt: "Casa VG", en: "Casa VG" },
    location: { pt: "Portugal", en: "Portugal" },
    year: "2024",
    category: { pt: "Residencial", en: "Residential" },
    description: {
      pt: "Projeto residencial com cozinha e sala de jantar em linguagem clássica contemporânea, madeira quente em espinha, iluminação integrada e sala de estar marcada por estantaria escultórica e materiais naturais.",
      en: "Residential project with a contemporary-classic kitchen and dining area, warm herringbone wood flooring, integrated lighting, and a living room defined by sculptural shelving and natural materials.",
    },
    images: [
      "/images/casa-vg/capa.jpg",
      "/images/casa-vg/02.jpg",
      "/images/casa-vg/16.jpg",
      "/images/casa-vg/04.jpg",
      "/images/casa-vg/05.jpg",
      "/images/casa-vg/08.jpg",
      "/images/casa-vg/09.jpg",
      "/images/casa-vg/10.jpg",
      "/images/casa-vg/12.jpg",
      "/images/casa-vg/14.jpg",
      "/images/casa-vg/15.jpg",
      "/images/casa-vg/19.jpg",
      "/images/casa-vg/20.jpg",
      "/images/casa-vg/23.jpg",
      "/images/casa-vg/26.jpg",
      "/images/casa-vg/18.jpg",
      "/images/casa-vg/21.jpg",
      "/images/casa-vg/27.jpg",
    ],
  },
  {
    slug: "casa-sn",
    title: { pt: "Casa SN", en: "Casa SN" },
    location: { pt: "Portugal", en: "Portugal" },
    year: "2024",
    category: { pt: "Residencial", en: "Residential" },
    description: {
      pt: "Projeto residencial de carácter intemporal: hall com ripado de madeira e separadores escultóricos, sala ampla com lareira a três faces e cozinha integrada em pedra e nogueira, complementada por um escritório-biblioteca com zona de leitura em arco. Madeira quente, tons cru e iluminação cénica dão coerência a todo o espaço.",
      en: "A timeless family home shaped by warm wood, raw tones and scenographic lighting. The entrance hall unfolds through vertical slats and sculptural dividers, opening into a generous living room anchored by a three-sided fireplace and a kitchen where stone meets walnut in quiet balance. A study-library extends the atmosphere with an arched reading nook — a place to pause, read and inhabit the light.",
    },
    images: [
      "/images/casa-sn/capa.jpg",
      "/images/casa-sn/01.jpg",
      "/images/casa-sn/02.jpg",
      "/images/casa-sn/03.jpg",
      "/images/casa-sn/04.jpg",
      "/images/casa-sn/05.jpg",
      "/images/casa-sn/06.jpg",
      "/images/casa-sn/07.jpg",
      "/images/casa-sn/08.jpg",
      "/images/casa-sn/09.jpg",
      "/images/casa-sn/10.jpg",
      "/images/casa-sn/11.jpg",
      "/images/casa-sn/12.jpg",
      "/images/casa-sn/13.jpg",
    ],
  },
  {
    slug: "tp",
    title: { pt: "Projeto PP", en: "Project PP" },
    location: { pt: "Portugal", en: "Portugal" },
    year: "2024",
    category: { pt: "Residencial", en: "Residential" },
    description: {
      pt: "Reabilitação integral de uma casa de família. Open space generoso onde cozinha, sala e refeições partilham a mesma luz, complementado por três quartos de atmosfera serena. Paleta neutra, madeira clara e detalhes em pedra dão continuidade entre os ambientes.",
      en: "Full renovation of a family home. A generous open space where kitchen, living and dining share the same light, complemented by three serene bedrooms. A neutral palette, light wood and stone details create continuity between spaces.",
    },
    images: [
      "/images/casa-tp/capa.jpg",
      "/images/casa-tp/02.jpg",
      "/images/casa-tp/03.jpg",
      "/images/casa-tp/04.jpg",
      "/images/casa-tp/05.jpg",
      "/images/casa-tp/06.jpg",
      "/images/casa-tp/07.jpg",
      "/images/casa-tp/08.jpg",
      "/images/casa-tp/09.jpg",
      "/images/casa-tp/10.jpg",
      "/images/casa-tp/11.jpg",
      "/images/casa-tp/12.jpg",
      "/images/casa-tp/13.jpg",
      "/images/casa-tp/14.jpg",
      "/images/casa-tp/15.jpg",
    ],
  },
  {
    slug: "sao-paio-apartments",
    title: { pt: "São Paio Apartments", en: "São Paio Apartments" },
    location: { pt: "Porto, Portugal", en: "Porto, Portugal" },
    year: "2024",
    category: { pt: "Residencial", en: "Residential" },
    description: {
      pt: "Apartamentos sobre o Douro, desenhados como um exercício de calma e luz. Uma sala ampla abre-se ao rio através de vãos generosos, prolongando-se numa cozinha-ilha em ónix verde que se torna peça central. Madeira de nogueira, têxteis cru e apontamentos em latão dão continuidade a todos os ambientes, culminando em quartos de atmosfera intimista — do bege sereno ao verde profundo.",
      en: "Apartments overlooking the Douro river, conceived as an exercise in calm and light. A generous living area opens to the river through wide glazing, extending into a kitchen island in green onyx that becomes the sculptural centrepiece. Walnut wood, raw textiles and brass accents thread continuity through every room, culminating in bedrooms of intimate atmosphere — from serene beige to deep green.",
    },
    images: [
      "/images/sao-paio-apartments/capa.jpeg",
      "/images/sao-paio-apartments/1.jpeg",
      "/images/sao-paio-apartments/2.jpeg",
      "/images/sao-paio-apartments/3.jpeg",
      "/images/sao-paio-apartments/4.jpeg",
      "/images/sao-paio-apartments/5.jpeg",
      "/images/sao-paio-apartments/6.jpeg",
      "/images/sao-paio-apartments/7.jpeg",
      "/images/sao-paio-apartments/8.jpeg",
      "/images/sao-paio-apartments/9.jpeg",
      "/images/sao-paio-apartments/10.jpeg",
      "/images/sao-paio-apartments/11.PNG",
      "/images/sao-paio-apartments/12.PNG",
      "/images/sao-paio-apartments/13.PNG",
    ],
  },
];
