import type { Project } from "./types";

export const projects: Project[] = [
  {
    slug: "vg",
    title: { pt: "Casa VG", en: "Casa VG" },
    location: { pt: "Portugal", en: "Portugal" },
    year: "2024",
    category: { pt: "Residencial", en: "Residential" },
    description: {
      pt: "Projeto residencial com cozinha e sala de jantar em linguagem clássica contemporânea, madeira quente em espinha, iluminação integrada e sala de estar marcada por estantaria escultórica e materiais naturais.",
      en: "Residential project with a contemporary-classic kitchen and dining area, warm herringbone wood flooring, integrated lighting, and a living room defined by sculptural shelving and natural materials.",
    },
    images: [
      "/images/casa-vg/cozinha-sala-03.webp",
      "/images/casa-vg/cozinha-sala-01.webp",
      "/images/casa-vg/cozinha-sala-02.webp",
      "/images/casa-vg/hall-quartos-01.webp",
      "/images/casa-vg/sala-estar-01.webp",
      "/images/casa-vg/sala-estar-02.webp",
      "/images/casa-vg/sala-estar-03.webp",
      "/images/casa-vg/sala-estar-04.webp",
    ],
  },
  {
    slug: "casa-sn",
    title: { pt: "Casa SN", en: "Casa SN" },
    location: { pt: "Portugal", en: "Portugal" },
    year: "2024",
    category: { pt: "Residencial", en: "Residential" },
    description: {
      pt: "Projeto residencial de carácter intemporal: hall com ripado de madeira e separadores escultóricos, sala ampla com lareira a três faces e cozinha integrada em pedra e nogueira, complementada por um escritório-biblioteca com zona de leitura em arco. Madeira quente, tons cru e iluminação cénica dão coerência a todo o espaço.",
      en: "A timeless family home shaped by warm wood, raw tones and scenographic lighting. The entrance hall unfolds through vertical slats and sculptural dividers, opening into a generous living room anchored by a three-sided fireplace and a kitchen where stone meets walnut in quiet balance. A study-library extends the atmosphere with an arched reading nook — a place to pause, read and inhabit the light.",
    },
    images: [
      "/images/casa-sn/sala-01.webp",
      "/images/casa-sn/sala-02.webp",
      "/images/casa-sn/hall-02.webp",
      "/images/casa-sn/sala-03.webp",
      "/images/casa-sn/sala-04-cozinha.webp",
      "/images/casa-sn/suite-02.webp",
      "/images/casa-sn/escrit-01.webp",
      "/images/casa-sn/escritorio-01.webp",
      "/images/casa-sn/escritorio-02.webp",
      "/images/casa-sn/escritorio-03.webp",
    ],
  },
  {
    slug: "tp",
    title: { pt: "Casa TP", en: "Casa TP" },
    location: { pt: "Portugal", en: "Portugal" },
    year: "2024",
    category: { pt: "Residencial", en: "Residential" },
    description: {
      pt: "Reabilitação integral de uma casa de família. Open space generoso onde cozinha, sala e refeições partilham a mesma luz, complementado por três quartos de atmosfera serena. Paleta neutra, madeira clara e detalhes em pedra dão continuidade entre os ambientes.",
      en: "Full renovation of a family home. A generous open space where kitchen, living and dining share the same light, complemented by three serene bedrooms. A neutral palette, light wood and stone details create continuity between spaces.",
    },
    images: [
      "/images/casa-tp/openspace-04.webp",
      "/images/casa-tp/hall-01.webp",
      "/images/casa-tp/cozinha-01.webp",
      "/images/casa-tp/cozinha-04.webp",
      "/images/casa-tp/suite-01.webp",
      "/images/casa-tp/quarto-mf-02.webp",
      "/images/casa-tp/quarto-pe-02.webp",
    ],
  },
  {
    slug: "foz-apartments",
    title: { pt: "Foz Apartments", en: "Foz Apartments" },
    location: { pt: "Portugal", en: "Portugal" },
    year: "2024",
    category: { pt: "Residencial", en: "Residential" },
    description: {
      pt: "Projeto integral de apartamentos com átrio em madeira escura, open space contínuo entre sala, jantar e cozinha, e três quartos de carácter próprio — do verde profundo ao azul sereno. Materiais naturais, ripado de madeira e têxteis suaves criam uma atmosfera intemporal.",
      en: "Full apartment project featuring a dark-wood entrance hall, a continuous open space across living, dining and kitchen, and three bedrooms with distinct characters — from deep green to serene blue. Natural materials, wooden slats and soft textiles create a timeless atmosphere.",
    },
    images: [
      "/images/foz-apartments/openspace-02.webp",
      "/images/foz-apartments/openspace-01.webp",
      "/images/foz-apartments/hall.webp",
      "/images/foz-apartments/openspace-03.webp",
      "/images/foz-apartments/quarto-01.webp",
      "/images/foz-apartments/quarto-01-02.webp",
      "/images/foz-apartments/quarto-02.webp",
      "/images/foz-apartments/quarto-02-02.webp",
      "/images/foz-apartments/quarto-03.webp",
    ],
  },
  {
    slug: "sao-paio-apartments",
    title: { pt: "São Paio Apartments", en: "São Paio Apartments" },
    location: { pt: "Porto, Portugal", en: "Porto, Portugal" },
    year: "2024",
    category: { pt: "Residencial", en: "Residential" },
    description: {
      pt: "Apartamentos sobre o Douro, desenhados como um exercício de calma e luz. Uma sala ampla abre-se ao rio através de vãos generosos, prolongando-se numa cozinha-ilha em ónix verde que se torna peça central. Madeira de nogueira, têxteis cru e apontamentos em latão dão continuidade a todos os ambientes, culminando em quartos de atmosfera intimista — do bege sereno ao verde profundo.",
      en: "Apartments overlooking the Douro river, conceived as an exercise in calm and light. A generous living area opens to the river through wide glazing, extending into a kitchen island in green onyx that becomes the sculptural centrepiece. Walnut wood, raw textiles and brass accents thread continuity through every room, culminating in bedrooms of intimate atmosphere — from serene beige to deep green.",
    },
    images: [
      "/images/sao-paio-apartments/img-4100.webp",
      "/images/sao-paio-apartments/img-4097.webp",
      "/images/sao-paio-apartments/img-4099.webp",
      "/images/sao-paio-apartments/img-4065.webp",
      "/images/sao-paio-apartments/img-4090.webp",
      "/images/sao-paio-apartments/img-4066.webp",
      "/images/sao-paio-apartments/img-4103.webp",
      "/images/sao-paio-apartments/img-4068.webp",
      "/images/sao-paio-apartments/img-4073.webp",
      "/images/sao-paio-apartments/view-01.webp",
      "/images/sao-paio-apartments/view-02.webp",
    ],
  },
];
