/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as EstudioRouteImport } from './routes/estudio'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjetosIndexRouteImport } from './routes/projetos.index'
import { Route as ProjetosSlugRouteImport } from './routes/projetos.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const EstudioRoute = EstudioRouteImport.update({
  id: '/estudio',
  path: '/estudio',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosIndexRoute = ProjetosIndexRouteImport.update({
  id: '/projetos/',
  path: '/projetos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosSlugRoute = ProjetosSlugRouteImport.update({
  id: '/projetos/$slug',
  path: '/projetos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/estudio': typeof EstudioRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/projetos/$slug': typeof ProjetosSlugRoute
  '/projetos/': typeof ProjetosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/estudio': typeof EstudioRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/projetos/$slug': typeof ProjetosSlugRoute
  '/projetos': typeof ProjetosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/estudio': typeof EstudioRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/projetos/$slug': typeof ProjetosSlugRoute
  '/projetos/': typeof ProjetosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacto'
    | '/estudio'
    | '/privacidade'
    | '/sitemap.xml'
    | '/projetos/$slug'
    | '/projetos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacto'
    | '/estudio'
    | '/privacidade'
    | '/sitemap.xml'
    | '/projetos/$slug'
    | '/projetos'
  id:
    | '__root__'
    | '/'
    | '/contacto'
    | '/estudio'
    | '/privacidade'
    | '/sitemap.xml'
    | '/projetos/$slug'
    | '/projetos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactoRoute: typeof ContactoRoute
  EstudioRoute: typeof EstudioRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ProjetosSlugRoute: typeof ProjetosSlugRoute
  ProjetosIndexRoute: typeof ProjetosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estudio': {
      id: '/estudio'
      path: '/estudio'
      fullPath: '/estudio'
      preLoaderRoute: typeof EstudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/': {
      id: '/projetos/'
      path: '/projetos'
      fullPath: '/projetos/'
      preLoaderRoute: typeof ProjetosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/$slug': {
      id: '/projetos/$slug'
      path: '/projetos/$slug'
      fullPath: '/projetos/$slug'
      preLoaderRoute: typeof ProjetosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactoRoute: ContactoRoute,
  EstudioRoute: EstudioRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ProjetosSlugRoute: ProjetosSlugRoute,
  ProjetosIndexRoute: ProjetosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
